---

  - name: Download docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_composer_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
      dest: /usr/local/bin/docker-compose-{{ docker_composer_version }}
      mode: 0755
    become: yes

  - name: Create docker-compose symlink
    file:
      src: /usr/local/bin/docker-compose-{{ docker_composer_version }}
      dest: /usr/local/bin/docker-compose
      state: link
    become: yes
