---

  - name: Add Ansible repository
    apt_repository:
      repo: ppa:ansible/ansible
      state: present
    become: yes

  - name: Install Ansible
    apt:
      name: ansible
      update_cache: yes
    become: yes
