---

  - name: Add Docker GPG key
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes

  - name: Add Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present
    become: yes

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes
    become: yes

  - name: Add docker group to boxkeeper
    user:
      name: boxkeeper
      append: yes
      groups: docker
    become: yes
